### ISSUE TITLE
Add Google-style NRQL calculated latency SLO option

### ISSUE THREAD

**Issue by andrewseling** [newrelic/nr1-slo-r#112]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Currently, the 'Latency' SLO type is calculated based on alert violation duration. I want to change or add an option to calculate Latency with NRQL similar to how the 'Error' SLO type already works.

## Desired Behaviour

I want to define Latency SLOs as ["The proportion of requests that were faster than some threshold."](https://landing.google.com/sre/workbook/chapters/implementing-slos/#a-worked-example) The threshold should be configurable. In many cases, I would like to define a p95 and p99 SLO against the same SLI.

In general, the user experience should be the same as creating an 'Error' SLO type, except with an additional field for threshold duration.

## Possible Solution

I believe generating a NRQL query similar to the one below from the GUI wizard will accomplish this goal. This query returns the percentage of requests with a duration under 5 seconds from a list of transactions provided by the user. The duration threshold and transactions should both be configurable by the user.

`SELECT (filter(count(*)), WHERE eventtype() = 'Transaction' AND duration < 5) / filter(count(*), WHERE eventtype() = 'Transaction'))*100 FROM Transaction WHERE {transactionNamesGoHere}`

(If this doesn't do what I think it does, please let me know!)

## Additional context
I can probably do the PR on this, but I wanted to open up discussion first to make sure I'm on the right track (and also to decide what to name the new SLO type). Any thoughts, concerns, or conflicts with other planned items I should be aware of?

@gem-wang This is the issue I referenced in our conversation this afternoon.
@kaprah, @t-morgan Please add any additional context or requirements I've missed.

**Comment by andrewseling** [comment]
I've been familiarizing myself with the code today, and it looks like there are two options for implementing this.

1. Copy the code already written for error budget SLOs and modify it to support latency SLOs. If the two are likely to diverge in the future, this might be cleaner, at the cost of repeating ourselves.

2. Modify the error budget code to accept 'duration > $variable' as a defect, and re-use the existing error budget code. Since I don't see any real difference between 'HTTP 500' and 'duration > $variable' when it comes to calculations and alerting, this seems like a better option.

Any thoughts? If not, I'll start working on the second option later this week.

**Comment by gem-wang** [comment]
@andrewseling I don't think I fully understand your second option. I think first option is good. We can parameterize the error budget calculation logic, and then provide an option to call that from latency SLO calculation as well. That way, we are not repeating ourselves, just provide another way of calculating latency.

**Comment by ricegi** [comment]
Hey @andrewseling - I was just testing the PR and ran into a couple of issues with the SLO definition. I am going to schedule some more time to review but it might be a couple of days before it gets merged. Just wanted to give you the the heads up.

**Comment by ricegi** [comment]
and thanks fort this submission, this is awesome!

**Comment by andrewseling** [comment]
@ricegi, not sure if you saw my comment on the PR - there are some calculation issues I haven't figured out yet. I'll mark the PR as ready to review when they are fixed. Thanks!
