### ISSUE TITLE
Improvement on the Transaction Filter

### ISSUE THREAD

**Issue by olwenya** [newrelic/nr1-slo-r#127]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
The transaction filter in the `Define SLO` form will only match names that begin with the input string.

## Desired Behaviour
The filter returns transaction names that contain the substring.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by khpeet** [comment]
@olwenya - I should have this fixed in the next merged PR

cc: @ricegi

**Comment by khpeet** [comment]
can be closed. Added in https://github.com/newrelic/nr1-slo-r/pull/133
