### ISSUE TITLE
Hardcoded Account ID

### ISSUE THREAD

**Issue by icpenguins** [newrelic/nr1-slo-r#148]
The account ID should not be hardcoded.

https://github.com/newrelic/nr1-slo-r/blob/bdefd359f371cba8f6a9e826b98f344b4b1ca636/nerdlets/shared/services/alert-policies.js#L14

**Comment by ricegi** [comment]
fix implemented - new version generation required ASAP - https://github.com/newrelic/nr1-slo-r/pull/149

**Comment by ricegi** [comment]
Fixed in 1.7.6
