### ISSUE TITLE
Launcher - Summary View

### ISSUE THREAD

**Issue by devfreddy** [newrelic/nr1-slo-r#40]
For each indicator (have a section per indicator):
- render a summary "row" summarizing each indicator (in-memory using row-level data)
- render a table or list of each SLO

```jsx
// Some psuedo-code

render () {
  return SLO_INDICATORS.map((indicator) => {
    return <>
      <IndicatorSummary></IndicatorSummary>
      <IndicatorTable></IndicatorTable>
    </>
  )
}
```

**Comment by ricegi** [comment]
@devfreddy - I really love the mock up you devises for this - especially the left hand nav that shows all the entities - a user shouldn't have to go into the entity explorer to view the SLOs - we can bring the entities and the SLOs to the user.

**Comment by devfreddy** [comment]
@danielgolden I forget where we landed on where/how to expose entities but wanted to make sure you saw @ricegi's comment above.

**Comment by devfreddy** [comment]
I remember now - each summary table is a row per entity, we'll give you a way to get to that entity from the row.

**Comment by norbertsuski** [comment]
@devfreddy @tangollama our understanding here is that we should split SLO/R Overview into 4 sections, each with table for Errors, Availability, Capacity and Latency?
