### ISSUE TITLE
Create Calendar View for each SLO

### ISSUE THREAD

**Issue by ricegi** [newrelic/nr1-slo-r#47]
Provide a Weekly / Monthly view for each SLO attainment calculation. 

## Summary

Provides a view of SLO attainment in the conventional calendar sense rather than the rolling current, 7 day, and 30 day window.

## Desired Behaviour

Possible toggle between calendar view and the current rolling SLO calculations. 

## Possible Solution

...

## Additional context

Most people will want to ahve a calendar view fo SLO attainment.

**Comment by norbertsuski** [comment]
@tangollama @ricegi let me put some example here: we can add "Show calendar" button/link next to "Open Entity" button which will open calendar with month view, where percentage of successfull transactions will be calculated and displayed for each day (with possibility to move to another month). Is this right?

![image](https://user-images.githubusercontent.com/5214156/88389935-c66d9100-cdb7-11ea-9735-fc7055c62f39.png)

**Comment by tangollama** [comment]
@norbertsuski correct.

**Comment by ricegi** [comment]
Ok - this is where we get into really expensive NRQL for constructing the view. In the past few weeks I've thought about caching the SLO results into another nerdstore doc - but that also seems needlessly complex. So, I am prototyping a Lamdba right now that will read in the SLOs for each entity and record the SLO metrics each day in Insights. I think this will be a far superior way to go forward with SLO/R and reduce the need to depend on doing all these calculations in the UI. We can leave the UI for config of the SLOs and Display of the SLO data in Insights.
