### ISSUE TITLE
Need way to define a new SLO from the Launcher

### ISSUE THREAD

**Issue by ricegi** [newrelic/nr1-slo-r#54]
## Summary

The definition of an SLO linked to a simple entity is too opaque - we need to make it easier to get to the SLO definition. In the case of Alert derived SLOs there is a really loose correlation between the entity and the Alert. So what's the point of limiting the definition of SLOs at the entity.

## Desired Behaviour

It is easy to define everything you need for an SLO in one place. 

## Possible Solution

TBD - modification of the SLO definition experience

**Comment by norbertsuski** [comment]
@ricegi let me summarize how I understand this in the use case:

1. User is able to create new SLO in current SLO/R Overview window (opened from Launcher)
2. There should be some button like "Create new SLO"
3. For Error-based alerts there should be a possibility to choose one of the entities from some list. For Alert-based there are some policies to be checked.

Do I understand it correctly? If not, could you briefly describe it as some step-by-step use case?
