### ISSUE TITLE
Error indicator not using correct field

### ISSUE THREAD

**Issue by remmizekim** [newrelic/nr1-slo-r#55]
When setting up an Error indicator SLO, it is filtering only on the `httpResponseCode` field and not including the `response.status` one. For at least .NET Framework agents, the `httpResponseCode` field is not populated but the `response.status` one is.

**Comment by jeffrey-hines** [comment]
I have this same issue.

**Comment by ricegi** [comment]
Thanks for reporting this this - the agent type will be using the default as you indicated above. That should be a quick fix.

**Comment by jbeveland27** [comment]
Closed by 53325df
