### ISSUE TITLE
Two SLO's based upon Error indicator in the same SLO group overwrite the defects selected in the dropdown

### ISSUE THREAD

**Issue by danifitz** [newrelic/nr1-slo-r#60]
## Description

When creating two SLO's in the same SLO group, if both use the Error indicator then changing the defects selected in the dropdown (5xx errors, 401-unauthorised etc) are shared between the two SLO's. For example if you wanted one SLO for 5xx errors and another for everything else, this is impossible because when you change one, the other is changed too.

## Steps to Reproduce

Have two Error SLO's in a single SLO group. They have different transactions selected. Set one to use 5XX defects, the other to use 401 - Unauthorised. Then change one Error SLO and add a new defect. You should observe they now BOTH have this defect selected.

## Expected Behaviour

I'd expect to be able to have two (or more) separate Error SLO's in an SLO group each scoped to different transactions and different defects (5xx, 401, 403 etc).

## Relevant Logs / Console output

None unfortunately.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
@datanerd/nr1/1.10.10 darwin-x64 node-v10.16.3
* Browser name and version:
Chrome 79 64 bit. Also observed on customer machine (versions unknown)
* Operating System and version:
Mac OS 10.14.3
## Additional context

None.

**Comment by danifitz** [comment]
Possibly related https://github.com/newrelic/nr1-slo-r/issues/61

**Comment by ricegi** [comment]
Should be addressed with rel 1.4.6
