### ISSUE TITLE
Error when editing an Error-based SLO

### ISSUE THREAD

**Issue by danifitz** [newrelic/nr1-slo-r#61]
## Description

When editing an existing Error SLO, I click on the three dots, then Edit. Add a new defect to an Error SLO and click Update Service, intermittently, it doesn't update. So I click back on Edit on the same SLO and the defect I added is not there.

## Steps to Reproduce

See description above.

## Expected Behaviour

When I add a new defect type to an existing Error SLO using the Edit option and click Update Service, any edits I make are persisted.

## Relevant Logs / Console output

When I click on the Update Service button, I observed this error in the console

```
single-document.js:25 Uncaught (in promise) TypeError: e.map is not a function
    at c (single-document.js:25)
    at s (single-document.js:33)
    at single-document.js:65
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.T.forEach.e.<computed> [as next] (runtime.js:97)
    at c (runtime.js:45)
    at t (runtime.js:135)
    at runtime.js:170
    at new Promise (<anonymous>)
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
@datanerd/nr1/1.10.10 darwin-x64 node-v10.16.3
* Browser name and version:
Chrome 79
* Operating System and version:
Mac OS 10.14.3

## Additional context

SLO Group had multiple Error SLO's defined within it.

**Comment by ricegi** [comment]
Should be addressed with rel 1.4.6
