### ISSUE TITLE
SLO Group dropdown is empty despite an SLO group being defined

### ISSUE THREAD

**Issue by danifitz** [newrelic/nr1-slo-r#64]
## Description

Have defined some SLO's in the entity view and those are contained within a group. However when you view the SLO/R nerdlet from the home page launcher view, the two drop downs to pick an SLO group to view are not populated.

## Steps to Reproduce

Create an SLO(s). Go to homepage, try to view it via the launcher view

## Expected Behaviour

I can view different SLO groups from the main launcher view. The groups are properly populated into the dropdown.

## Relevant Logs / Console output

None.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
@datanerd/nr1/1.10.10 darwin-x64 node-v10.16.3
* Browser name and version:
Chrome 79
* Operating System and version:
Mac OS 10.14.3

**Comment by ricegi** [comment]
related to issue 78 ... getting fixed

**Comment by ricegi** [comment]
fixed in release 1.5.1 - requires that the SLOs defined need to be resaved to ensure the slor=true tag is added to the entity.
