### ISSUE TITLE
Replace appName with entityGuid in the queries and SLO definitions

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-slo-r#98]
appName is referenced throughout the current (1.x) documents and queries. We need to: 

- shift to entityGuid as the identifier for events
- store the entityGuid in the slo docs
- implement in a way that supports backwards compatibility with the 1.x definitions

**Comment by norbertsuski** [comment]
@tangollama could you please describe it more? I'm not sure I understand correctly, because right now is both entityGuid and appName in SLO document:

![image](https://user-images.githubusercontent.com/5214156/89647763-63ebb900-d8be-11ea-8dcd-6d66075bd630.png)

**Comment by tangollama** [comment]
@norbertsuski, thanks for the clarification. I'll do a bit more research and re-address.
